### ISSUE TITLE
regarding: "// all properties MUST be given values, see edge cases section below"

### ISSUE THREAD

**Issue by Obiwarn** [nathanstitt/modeled-mobx#1]
I had the same problem, check this out:

https://mobx.js.org/installation.html#use-spec-compliant-transpilation-for-class-properties

**Comment by nathanstitt** [comment]
Oh that's really interesting!  thanks so much for pointing that out. I'll update the README to mention this.  In my case we're using it mostly from typescript where most of the properties should have a default value in order for them to be properly typed, so it hasn't affected us too much.
